DEF_ERR(BUFFER_OVERFLOW, 0)

DEF_ERR(WRONG_TAIL_USAGE, 1)     

DEF_ERR(INVALID_INPUT_INDEX , 2)  

DEF_ERR(ATTEMPT_TO_DELETE_AFTER_TAIL, 3)

DEF_ERR(ATTEMPT_TO_DELETE_BEFORE_HEAD, 4)

DEF_ERR(NO_ELEMENT_BY_THIS_LOGICAL_ORDER, 5)

DEF_ERR(ADD_AFTER_FREE_ELEMENT, 6)       

DEF_ERR(DELETE_FREE_ELEMENT, 7)

DEF_ERR(CAPACITY_BELOW_ZERO , 8)

DEF_ERR(LIST_IS_NULL, 9)

DEF_ERR(INCORRECT_OPERATION, 10)

DEF_ERR(ATTEMPT_TO_MASH_WITH_RESIZE, 11)